"""tao_bang_tau_ca

Revision ID: a76140570a8a
Revises: 5aed4db515e3
Create Date: 2026-05-15 09:32:55.493952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a76140570a8a'
down_revision: Union[str, Sequence[str], None] = '5aed4db515e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tau_ca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('so_hieu', sa.String(length=50), nullable=False),
    sa.Column('chu_tau', sa.String(length=100), nullable=False),
    sa.Column('chieu_dai', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tau_ca_id'), 'tau_ca', ['id'], unique=False)
    op.create_index(op.f('ix_tau_ca_so_hieu'), 'tau_ca', ['so_hieu'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tau_ca_so_hieu'), table_name='tau_ca')
    op.drop_index(op.f('ix_tau_ca_id'), table_name='tau_ca')
    op.drop_table('tau_ca')
    # ### end Alembic commands ###
