"""add_vessel_details_and_specs

Revision ID: dfbea989296b
Revises: f726ff9e25ae
Create Date: 2026-07-10 10:22:40.258827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfbea989296b'
down_revision: Union[str, None] = 'f726ff9e25ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vessel_inspections', sa.Column('build_year', sa.String(length=50), nullable=True))
    op.add_column('vessel_inspections', sa.Column('build_place', sa.String(length=255), nullable=True))
    op.add_column('vessel_inspections', sa.Column('gross_tonnage', sa.Float(), nullable=True))
    op.add_column('vessel_inspections', sa.Column('crew_limit', sa.Integer(), nullable=True))
    op.add_column('vessel_inspections', sa.Column('bmax', sa.Float(), nullable=True))
    op.add_column('vessel_inspections', sa.Column('depth', sa.Float(), nullable=True))
    op.add_column('vessel_inspections', sa.Column('engine_model', sa.String(length=100), nullable=True))
    op.add_column('vessel_inspections', sa.Column('engine_serial', sa.String(length=100), nullable=True))
    op.add_column('vessel_inspections', sa.Column('engine_build_info', sa.String(length=255), nullable=True))
    op.add_column('vessel_inspections', sa.Column('allowed_area', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vessel_inspections', 'allowed_area')
    op.drop_column('vessel_inspections', 'engine_build_info')
    op.drop_column('vessel_inspections', 'engine_serial')
    op.drop_column('vessel_inspections', 'engine_model')
    op.drop_column('vessel_inspections', 'depth')
    op.drop_column('vessel_inspections', 'bmax')
    op.drop_column('vessel_inspections', 'crew_limit')
    op.drop_column('vessel_inspections', 'gross_tonnage')
    op.drop_column('vessel_inspections', 'build_place')
    op.drop_column('vessel_inspections', 'build_year')
    # ### end Alembic commands ###
