"""add_technical_status

Revision ID: f726ff9e25ae
Revises: 20260615_0003
Create Date: 2026-07-04 22:29:44.804083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f726ff9e25ae'
down_revision: Union[str, None] = '20260615_0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vessel_inspections', sa.Column('technical_status', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vessel_inspections', 'technical_status')
    # ### end Alembic commands ###
